server:
  port: ${ORDER_SERVICE_PORT:8084}
  servlet:
    contextPath: /v1

spring:
  config:
    activate:
      on-profile: default
  application:
    name: order-service
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer