server:
  port: ${ORDER_DETAIL_SERVICE_PORT:8085}
  servlet:
    contextPath: /v1

spring:
  config:
    activate:
      on-profile: default
  application:
    name: order-detail-service
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9092,localhost:9091
    streams:
      application-id: order-detail-service
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 3000
        spring.json.trusted.packages: com.example.order.message